source = ~/.config/hypr/hyprlock/colors.conf

general {
    hide_cursor = true
    ignore_empty_input = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

# ─── Background ──────────────────────────────────────────────────────────────
background {
    path = $background_image
    blur_passes = 3
    blur_size = 5
    brightness = 0.7
    contrast = 1.2
    vibrancy = 0.2
}

# ─── Avatar ──────────────────────────────────────────────────────────────────
image {
    monitor = HDMI-A-1
    path = ~/.face
    size = 130
    rounding = -1
    border_size = 3
    border_color = $entry_border_color
    position = 0%, 20%
    halign = center
    valign = center
}
image {
    monitor = DP-1
    path = ~/.face
    size = 170
    rounding = -1
    border_size = 3
    border_color = $entry_border_color
    position = 0%, 20%
    halign = center
    valign = center
}

# ─── Input field ─────────────────────────────────────────────────────────────
input-field {
    size = 13%, 4.5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0)
    outer_color = rgba(bd93f9ff) rgba(8be9fdff) 45deg
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg
    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 0
    font_family = $font_family
    placeholder_text =  ACCESS CODE
    fail_text = $PAMFAIL
    dots_spacing = 0.3
    position = 0%, -12%
    halign = center
    valign = center
}

# ─── Shape ───────────────────────────────────────────────────────────────────
shape {
    size = 41%, 41%
    color = rgba(282a36cc)
    rounding = 0
    border_size = 3
    border_color = rgba(bd93f9ff)
    position = 0%, 0%
    halign = center
    valign = center
}

# ─── Quote — 1080p ───────────────────────────────────────────────────────────
label {
    monitor = HDMI-A-1
    text = // SEE YOU SPACE COWBOY //
    font_size = 15
    font_family = $font_family
    position = 0%, 11%
    halign = center
    valign = center
    color = rgb(bd93f9)
}
# ─── Quote — 1440p ───────────────────────────────────────────────────────────
label {
    monitor = DP-1
    text = // SEE YOU SPACE COWBOY //
    font_size = 20
    font_family = $font_family
    position = 0%, 11%
    halign = center
    valign = center
    color = rgb(bd93f9)
}

# ─── Clock — 1080p ───────────────────────────────────────────────────────────
label {
    monitor = HDMI-A-1
    text = cmd[update:1000] date +"%H  :  %M  :  %S"
    font_size = 90
    font_family = Deltarune
    color = rgb(50fa7b)
    position = 0%, 4%
    halign = center
    valign = center
}
# ─── Clock — 1440p ───────────────────────────────────────────────────────────
label {
    monitor = DP-1
    text = cmd[update:1000] date +"%H  :  %M  :  %S"
    font_size = 120
    font_family = Deltarune
    color = rgb(50fa7b)
    position = 0%, 4%
    halign = center
    valign = center
}

# ─── Date — 1080p ────────────────────────────────────────────────────────────
label {
    monitor = HDMI-A-1
    text = cmd[update:60000] LC_TIME=C date +"%A, %d %B %Y"
    font_size = 15
    font_family = $font_family
    position = 0%, -1.5%
    halign = center
    valign = center
}
# ─── Date — 1440p ────────────────────────────────────────────────────────────
label {
    monitor = DP-1
    text = cmd[update:60000] LC_TIME=C date +"%A, %d %B %Y"
    font_size = 20
    font_family = $font_family
    position = 0%, -1.5%
    halign = center
    valign = center
}
