# =============================================================================
# Hypridle — Idle management daemon
# =============================================================================

general {
    lock_cmd = pidof hyprlock || hyprlock-wall
    before_sleep_cmd = pidof hyprlock || (hyprlock-wall & sleep 0.5)
    after_sleep_cmd = hyprctl dispatch dpms on
}

# ─── Lock screen ─────────────────────────────────────────────────────────────
# 10 min → lock the session
listener {
    timeout = 600
    on-timeout = hyprlock-wall
}

# ─── DPMS off ────────────────────────────────────────────────────────────────
# 10 min 30 s → turn off monitors
listener {
    timeout = 630
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# ─── Suspend (not working well)───────────────────────────────────────────────
# 30 min → suspend to RAM
#listener {
#    timeout = 1800
#    on-timeout = systemctl suspend
#}
