# This file sources other files in `hyprland` and `shared` folders
# You wanna add your stuff in files in `shared`

$profile = ii

source = $profile/hyprland.conf

# --- Shared configuration for all profiles ---
source=shared/env.conf
source=shared/variables.conf
source=shared/execs.conf
source=shared/general.conf
source=shared/rules.conf
source=shared/keybinds.conf
