# This file sources other files in `hyprland` and `shared` folders
# You wanna add your stuff in files in `shared`

$profile = caelestia

source = $profile/hyprland.conf

# --- Shared configuration for all profiles ---
source=shared/env.conf
source=shared/variables.conf
source=shared/execs.conf
source=shared/general.conf
source=shared/rules.conf
source=shared/keybinds.conf

# HyprMod managed settings
source = /home/gazzd/.config/hypr/hyprland-gui.conf
