# hyprlang noerror false
# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
exec-once = fcitx5

# Reload Hyprland plugins
exec-once = hyprpm reload -n

# Activate overview
exec-once = qs -c overview

# --- From caelestia ---

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Auto delete trash 30 days old
exec-once = trash-empty 30

# Forward bluetooth media commands to MPRIS
exec-once = mpris-proxy

# --- From ii ---

# Core components (authentication, lock screen)
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = hypridle

# Audio
exec-once = easyeffects --hide-window --service-mode
