# hyprlang noerror false
# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area

# HDMI port: mirror display. To see device name, use `hyprctl monitors`

# Blur
$blurEnabled = true
$blurSpecialWs = true
$blurPopups = true
$blurInputMethods = true
$blurSize = 8
$blurPasses = 2
$blurXray = false

# Shadow
$shadowEnabled = true
$shadowRange = 20
$shadowRenderPower = 3

# Gaps
$workspaceGaps = 10
$windowGapsIn = 10
$windowGapsOut = 20
$singleWindowGapsOut = 20

# Window styling
$windowOpacity = 0.95
$windowRounding = 10

$windowBorderSize = 3
$activeWindowBorderColour = rgba(255,0,0,1)
$inactiveWindowBorderColour = rgba(255,255,0,1)

input {
    kb_layout = us
    kb_variant = altgr-intl
    kb_options = altwin:meta_alt,lv3:alt_switch
    numlock_by_default = true
    repeat_delay = 250
    repeat_rate = 35

    follow_mouse = 1
    off_window_axis_events = 2

    touchpad {
        natural_scroll = yes
        disable_while_typing = true
        clickfinger_behavior = true
        scroll_factor = 0.7
    }
}

general {
    layout = dwindle

    allow_tearing = false  # Allows `immediate` window rule to work

    gaps_workspaces = $workspaceGaps
    gaps_in = $windowGapsIn
    gaps_out = $windowGapsOut
    border_size = $windowBorderSize

    #col.active_border = $activeWindowBorderColour
    #col.inactive_border = $inactiveWindowBorderColour
}

decoration {
    rounding = $windowRounding

    blur {
        enabled = $blurEnabled
        xray = $blurXray
        special = $blurSpecialWs
        ignore_opacity = true  # Allows opacity blurring
        new_optimizations = true
        popups = $blurPopups
        input_methods = $blurInputMethods
        size = $blurSize
        passes = $blurPasses
    }

}
